services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Moscow

  jenkins-agent:
    image: jenkins/inbound-agent:jdk17
    container_name: jenkins-agent
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_SECRET=e5078cc56c6758955ad4211b344785a92fd24d26b1907ffb2ef4a979b55b638d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nexus-data:/nexus-data
